version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  worker:
    depends_on:
      - redis
    build:
      context: ./worker 
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  api:
    depends_on:
      - postgres
      - redis
    build:
      context: ./api 
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  frontend:
    depends_on:
      - api
    build:
      context: ./frontend 
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
  nginx:
    depends_on:
      - frontend
      - api
    restart: always
    build:
      context: ./nginx 
      dockerfile: Dockerfile.dev
    ports:
      - '8080:80'
